language:
- generic
sudo: true
dist: trusty
before_install:
- sudo apt-get update -qq
- sudo apt-get install texlive-latex-base
script:
- mkdir build
- pdflatex -output-directory build main.tex
before_deploy:
- git fetch --tags
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: MKLXbDZZxZwPQhrK09SD4YJeBL4HS9wrbEac+MxWH536gRyn6HqzepIIE9tUCGTOtRISqIuY/LC5BuK+mWGPa0V2Pl9FtEIIlhs0wmqRUTOzTmsr624qeGNyaw84LkRzxJAbrwNNnKVt4dYbUeatDiwH/RldctHh6yH1G8l9xOWh2U+/ZqwiFmOG7aQ381m/qzpKQkbep4d5wl2u4WhickiLmBUYwpe86tRGY9w0h9N91awrDWBSbqPmyRS+1Wjh5ZqBhHD4chBZ8kJFGfomE0UFg3J4JeWOFZxKTui7NqdJQeTsXUfwc7sby037uiwL/XTOqJp0z0lwkHiEhxaFpK5Eym9wzw4YFOZqVbmnaDa/YyFvKIKT10iVony9E6hmLN1TVg/AzRm1gaMAZzAeFEb3fOm9EV1F0QLaafL02tXCClg2gQ3Daq/HCkDmM+JKrLI7892JV5oJzbbr2Dzd6SZJzVlaWjbAp9xb0rAoqmovmNdEQOOD5BUXR1Wsz/J2VQDqY+quyu06h0xthPVFjT6/94PtEzy7/fMtJTlIIBAppJNk07DTpShmxTCTedugQGehtcsSSV4x6mYJSdAZCvoZfmWh55EMtx3LJY95VA96L8lsq2ptEKZxfu5DAyZM44e9ucYZdo4+AZpePBJsBlFPEx+ErsRfBDU7Blx11BQ=
  file: build/main.pdf
  on:
    all_branches: true
    tags: true
